### ISSUE TITLE
Regarding Custom Listener to restart a failed job( tutorials/advanced)

### ISSUE THREAD

**Issue by gamebecks** [EasyBatch/easybatch-tutorials#3]
The custom listener seems to be identifying the records written before the job failed but the restart process still prints the records that were meant to be skipped.

Test Case: Steps are:
1. let the job fail as it happens via randomly throwing exception. Job fails and only initial three records get printed in the output csv file ( tweets-out.csv).
2. The checkpoint.oplog file contains the necessary detail ( status as FAILED and last written record number as 3)
3. delete the tweets-out.csv file from the target folder.
4.rerun the program (launcher.java) to get completed status.
Expected result: New tweets-out.csv file will be created with only record 4 and 5( as initial three will be skipped).
Actual result : New tweets-out.csv file is created but it has all five records written.

Please revert back asap.

**Comment by benas** [comment]
Hi,

Thank you for reporting this. Let me try to run your scenario and keep you informed.

Kr
Mahmoud

**Comment by gamebecks** [comment]
Thanks for the response. Actually I have an urgent requirement to implement incremental record processing after a job fail. Hence request to sort this out asap.

Regards

**Comment by gamebecks** [comment]
Hi Mahmoud,
                     Any update on the issue? Were you able to replicate at your end?

**Comment by gamebecks** [comment]
I have used a workaround for this.
Inside beforeRecordProcessing(Record record)  method, instead of returning null for the records to be skipped, I have rather stored such records in a List. And finally returned records as such for all.
Then in the beforeRecordWriting(Batch batch) method, I have iterated that list and for each such record,
have called batch.removeRecord(final Record record).

The result is as desired.

Thanks

**Comment by benas** [comment]
Hi,

Sorry for the late reply, I was on holidays.

Thank you for reporting this! Indeed, this is a bug in easy batch.

when the pipeline listener returns null to skip a record, it is ignored and the record is still processed.

I will fix this asap and release it in the upcoming v5.1.
I will keep you informed anyway.

Kr,
Mahmoud

**Comment by gamebecks** [comment]
Hi Mahmoud,
                      Thanks for the reply.
 In addition to records( meant to be skipped) still being processed, also the writer seems to be generating a new output file (tweets-out.csv) every time the job is run. 
I think ideally for batch fail scenario, rerun should not only write incremental records but also in the same output file which gets created in the first ( but failed job) run.

Regards

**Comment by benas** [comment]
Yes, I also noticed this. In the tutorial, the writer should opened in "append" mode. But this is a minor issue related to the tutorial implementation (not like the major issue about the listener which is related to the framework itself).

I will fix both issues and keep you posted.

**Comment by gamebecks** [comment]
Hi Mahmoud,
                     Is their any way by which job execution could be terminated explicitly?
Regards

**Comment by benas** [comment]
Hello,

This will possible in next version.

Work in progress here:

https://github.com/EasyBatch/easybatch-framework/commit/1674c3b569d8869e2bfb14ce121dc48eb762ee23

Keep tuned for v5.1 !

Kr
Mahmoud

**Comment by benas** [comment]
Hi @gamebecks 

I've published v5.1.0-SNAPSHOT with the fix.

Now, when I delete the file and restart the job, only records 4 and 5 are written. Which means that records 1..3 are effectively skipped.

BTW, I also updated the tutorial to open the record writer in append mode.

It would be great if you could give it a try and tell me if this is ok for you.

Kr
Mahmoud

**Comment by gamebecks** [comment]
Hi Mahmoud,
                     I took complete source code from the link - https://github.com/EasyBatch/easybatch-tutorials>'Get Source Code'.
But the problem still persists. All the records seem to be written again and not in append mode.

If the modified source code is placed somewhere else, do share the link.
BTW could you also please mention what files have you changed( or will change) to solve this bug.
This is required to update our build dependencies.

Thanks

**Comment by benas** [comment]
Hello,

Have you changed easy batch version to 5.1.0-SNAPSHOT in the tutorials' dependencies?

Here is how to proceed:

$>git clone https://github.com/EasyBatch/easybatch-tutorials.git (you may already downloaded and extracted the zip)
$>cd easybatch-tutorials

Edit the `pom.xml` file and change `<version>5.0.0</version>` to `<version>5.1.0-SNAPSHOT</version>`

$>mvn clean install

Then run the tutorial. Let me know if this helps.

Kr
Mahmoud

**Comment by gamebecks** [comment]
Hi Mahmoud,
                         Changed the easy batch version in pom.xml but still on clean install., i get dependency error as follows :
[ERROR] Failed to execute goal on project easybatch-tutorials: Could not resolve dependencies for project org.easybatch:easybatch-tutorials:jar:5.1.0-SNAPSHOT: The following artifacts could not be resolved: org.easybatch:easybatch-core:jar:5.1.0-SNAPSHOT ....................


Are you sure that the maven repository has something for 5.1.0-SNAPSHOT
Regards

**Comment by benas** [comment]
Oh sorry for that. But I'm sure:

https://oss.sonatype.org/content/repositories/snapshots/org/easybatch/easybatch-core/

Last snapshot version uploaded on Sun May 07 23:19:29 UTC 2017

Another user was able to use test it: https://github.com/EasyBatch/easybatch-framework/issues/277#issuecomment-299678627

**Comment by gamebecks** [comment]
Hi Mahmoud,
                     Attached at the bottom is the content  of  easybatch-tutorial-masters/pom.xml. As you can see, I have changed version to 5.1.0-SNAPSHOT only for <artifact id> easybatch-core </artifact id>.

Also I have downloaded all the jars and pom files from https://oss.sonatype.org/content/repositories/snapshots/org/easybatch/easybatch-core/5.1.0-SNAPSHOT/
to my local maven repository \maven_repo\org\easybatch\easybatch-core\5.1.0-SNAPSHOT.

But on clean install, I get build failure and the reason mentioned is : 
The POM for org.easybatch:easybatch-core:jar:5.1.0-SNAPSHOT is missing, no dependency information available.

Please help.



Content of easybatch-tutorial-masters/pom.xml-

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <groupId>org.easybatch</groupId>
    <artifactId>easybatch-tutorials</artifactId>
    <version>5.0.0</version>
    <packaging>jar</packaging>

    <name>easybatch-tutorials</name>
    <description>Easy Batch tutorials</description>
    <url>http://www.easybatch.org</url>

    <properties>
        <exec-maven-plugin-version>1.4.0</exec-maven-plugin-version>
        <hsqldb.version>2.3.4</hsqldb.version>
        <spring.version>4.3.3.RELEASE</spring.version>
        <hibernate-core.version>4.3.11.Final</hibernate-core.version>
        <javax.json.version>1.0.4</javax.json.version>
        <gson.version>2.4</gson.version>
        <activemq-core.version>5.7.0</activemq-core.version>
        <elasticsearch.version>1.7.3</elasticsearch.version>
        <commons-io.version>2.4</commons-io.version>
        <mongodb-driver.version>3.1.0</mongodb-driver.version>
        <maven-dependency-plugin.version>2.10</maven-dependency-plugin.version>
    </properties>

    <developers>
        <developer>
            <id>benas</id>
            <name>Mahmoud Ben Hassine</name>
            <url>http://benas.github.io</url>
            <email>mahmoud.benhassine@icloud.com</email>
            <roles>
                <role>Project founder</role>
            </roles>
        </developer>
    </developers>

    <licenses>
        <license>
            <name>MIT License</name>
            <url>http://opensource.org/licenses/mit-license.php</url>
        </license>
    </licenses>

    <dependencies>

        <dependency>
            <groupId>org.easybatch</groupId>
            <artifactId>easybatch-core</artifactId>
            <version>5.1.0-SNAPSHOT</version>
        </dependency>

        <dependency>
            <groupId>org.easybatch</groupId>
            <artifactId>easybatch-flatfile</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>org.easybatch</groupId>
            <artifactId>easybatch-xml</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>org.easybatch</groupId>
            <artifactId>easybatch-jdbc</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>org.easybatch</groupId>
            <artifactId>easybatch-hibernate</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>org.easybatch</groupId>
            <artifactId>easybatch-validation</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>org.easybatch</groupId>
            <artifactId>easybatch-tools</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>org.easybatch</groupId>
            <artifactId>easybatch-quartz</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>org.easybatch</groupId>
            <artifactId>easybatch-spring</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>org.easybatch</groupId>
            <artifactId>easybatch-jms</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>org.easybatch</groupId>
            <artifactId>easybatch-json</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>org.easybatch</groupId>
            <artifactId>easybatch-mongodb</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>org.easybatch</groupId>
            <artifactId>easybatch-xstream</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>org.hsqldb</groupId>
            <artifactId>hsqldb</artifactId>
            <version>${hsqldb.version}</version>
        </dependency>

        <dependency>
            <groupId>org.hibernate</groupId>
            <artifactId>hibernate-core</artifactId>
            <version>${hibernate-core.version}</version>
        </dependency>

        <dependency>
            <groupId>org.glassfish</groupId>
            <artifactId>javax.json</artifactId>
            <version>${javax.json.version}</version>
        </dependency>

        <dependency>
            <groupId>com.google.code.gson</groupId>
            <artifactId>gson</artifactId>
            <version>${gson.version}</version>
        </dependency>

        <dependency>
            <groupId>org.apache.activemq</groupId>
            <artifactId>activemq-core</artifactId>
            <version>${activemq-core.version}</version>
        </dependency>

        <dependency>
            <groupId>org.elasticsearch</groupId>
            <artifactId>elasticsearch</artifactId>
            <version>${elasticsearch.version}</version>
        </dependency>

        <dependency>
            <groupId>commons-io</groupId>
            <artifactId>commons-io</artifactId>
            <version>${commons-io.version}</version>
        </dependency>

        <dependency>
            <groupId>org.mongodb</groupId>
            <artifactId>mongodb-driver</artifactId>
            <version>${mongodb-driver.version}</version>
        </dependency>

        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-jdbc</artifactId>
            <version>${spring.version}</version>
        </dependency>

    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.3</version>
                <configuration>
                    <verbose>true</verbose>
                    <source>1.7</source>
                    <target>1.7</target>
                    <showWarnings>true</showWarnings>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-dependency-plugin</artifactId>
                <version>${maven-dependency-plugin.version}</version>
                <executions>
                    <execution>
                        <id>copy</id>
                        <phase>package</phase>
                        <goals>
                            <goal>copy-dependencies</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

    <profiles>

        
        <profile>
            <id>runHelloWorldTutorial</id>
            <build>
                <defaultGoal>exec:java</defaultGoal>
                <plugins>
                    <plugin>
                        <groupId>org.codehaus.mojo</groupId>
                        <artifactId>exec-maven-plugin</artifactId>
                        <version>${exec-maven-plugin-version}</version>
                        <configuration>
                            <mainClass>org.easybatch.tutorials.basic.helloworld.Launcher</mainClass>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <profile>
            <id>runWordCountTutorial</id>
            <build>
                <defaultGoal>exec:java</defaultGoal>
                <plugins>
                    <plugin>
                        <groupId>org.codehaus.mojo</groupId>
                        <artifactId>exec-maven-plugin</artifactId>
                        <version>${exec-maven-plugin-version}</version>
                        <configuration>
                            <mainClass>org.easybatch.tutorials.basic.wordcount.Launcher</mainClass>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>


        
        <profile>
            <id>runCsv2xmlTutorial</id>
            <build>
                <defaultGoal>exec:java</defaultGoal>
                <plugins>
                    <plugin>
                        <groupId>org.codehaus.mojo</groupId>
                        <artifactId>exec-maven-plugin</artifactId>
                        <version>${exec-maven-plugin-version}</version>
                        <configuration>
                            <mainClass>org.easybatch.tutorials.intermediate.csv2xml.Launcher</mainClass>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <profile>
            <id>runJdbcImportDataTutorial</id>
            <build>
                <defaultGoal>exec:java</defaultGoal>
                <plugins>
                    <plugin>
                        <groupId>org.codehaus.mojo</groupId>
                        <artifactId>exec-maven-plugin</artifactId>
                        <version>${exec-maven-plugin-version}</version>
                        <configuration>
                            <mainClass>org.easybatch.tutorials.intermediate.load.Launcher</mainClass>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <profile>
            <id>runJdbcExportDataTutorial</id>
            <build>
                <defaultGoal>exec:java</defaultGoal>
                <plugins>
                    <plugin>
                        <groupId>org.codehaus.mojo</groupId>
                        <artifactId>exec-maven-plugin</artifactId>
                        <version>${exec-maven-plugin-version}</version>
                        <configuration>
                            <mainClass>org.easybatch.tutorials.intermediate.extract.Launcher</mainClass>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <profile>
            <id>runElasticSearchTutorial</id>
            <build>
                <defaultGoal>exec:java</defaultGoal>
                <plugins>
                    <plugin>
                        <groupId>org.codehaus.mojo</groupId>
                        <artifactId>exec-maven-plugin</artifactId>
                        <version>${exec-maven-plugin-version}</version>
                        <configuration>
                            <mainClass>org.easybatch.tutorials.intermediate.elasticsearch.Launcher</mainClass>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>

        
        <profile>
            <id>runRecipesTutorial</id>
            <build>
                <defaultGoal>exec:java</defaultGoal>
                <plugins>
                    <plugin>
                        <groupId>org.codehaus.mojo</groupId>
                        <artifactId>exec-maven-plugin</artifactId>
                        <version>${exec-maven-plugin-version}</version>
                        <configuration>
                            <mainClass>org.easybatch.tutorials.advanced.recipes.Launcher</mainClass>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <profile>
            <id>runCustomMetricTutorial</id>
            <build>
                <defaultGoal>exec:java</defaultGoal>
                <plugins>
                    <plugin>
                        <groupId>org.codehaus.mojo</groupId>
                        <artifactId>exec-maven-plugin</artifactId>
                        <version>${exec-maven-plugin-version}</version>
                        <configuration>
                            <mainClass>org.easybatch.tutorials.advanced.metric.Launcher</mainClass>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <profile>
            <id>runCheckPointListenerTutorial</id>
            <build>
                <defaultGoal>exec:java</defaultGoal>
                <plugins>
                    <plugin>
                        <groupId>org.codehaus.mojo</groupId>
                        <artifactId>exec-maven-plugin</artifactId>
                        <version>${exec-maven-plugin-version}</version>
                        <configuration>
                            <mainClass>org.easybatch.tutorials.advanced.restart.Launcher</mainClass>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <profile>
            <id>runParallelProcessingWithForkJoin</id>
            <build>
                <defaultGoal>exec:java</defaultGoal>
                <plugins>
                    <plugin>
                        <groupId>org.codehaus.mojo</groupId>
                        <artifactId>exec-maven-plugin</artifactId>
                        <version>${exec-maven-plugin-version}</version>
                        <configuration>
                            <mainClass>org.easybatch.tutorials.advanced.parallel.ForkJoin</mainClass>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <profile>
            <id>runParallelProcessingWithLogicalPartitions</id>
            <build>
                <defaultGoal>exec:java</defaultGoal>
                <plugins>
                    <plugin>
                        <groupId>org.codehaus.mojo</groupId>
                        <artifactId>exec-maven-plugin</artifactId>
                        <version>${exec-maven-plugin-version}</version>
                        <configuration>
                            <mainClass>org.easybatch.tutorials.advanced.parallel.LogicalPartitions</mainClass>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <profile>
            <id>runParallelProcessingWithPhysicalPartitions</id>
            <build>
                <defaultGoal>exec:java</defaultGoal>
                <plugins>
                    <plugin>
                        <groupId>org.codehaus.mojo</groupId>
                        <artifactId>exec-maven-plugin</artifactId>
                        <version>${exec-maven-plugin-version}</version>
                        <configuration>
                            <mainClass>org.easybatch.tutorials.advanced.parallel.PhysicalPartitions</mainClass>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <profile>
            <id>runFilesParallelProcessingTutorial</id>
            <build>
                <defaultGoal>exec:java</defaultGoal>
                <plugins>
                    <plugin>
                        <groupId>org.codehaus.mojo</groupId>
                        <artifactId>exec-maven-plugin</artifactId>
                        <version>${exec-maven-plugin-version}</version>
                        <configuration>
                            <mainClass>org.easybatch.tutorials.advanced.cbrd.Launcher</mainClass>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <profile>
            <id>runQuartzTutorial</id>
            <build>
                <defaultGoal>exec:java</defaultGoal>
                <plugins>
                    <plugin>
                        <groupId>org.codehaus.mojo</groupId>
                        <artifactId>exec-maven-plugin</artifactId>
                        <version>${exec-maven-plugin-version}</version>
                        <configuration>
                            <mainClass>org.easybatch.tutorials.advanced.quartz.Launcher</mainClass>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <profile>
            <id>runSpringTutorial</id>
            <build>
                <defaultGoal>exec:java</defaultGoal>
                <plugins>
                    <plugin>
                        <groupId>org.codehaus.mojo</groupId>
                        <artifactId>exec-maven-plugin</artifactId>
                        <version>${exec-maven-plugin-version}</version>
                        <configuration>
                            <mainClass>org.easybatch.tutorials.advanced.spring.Launcher</mainClass>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <profile>
            <id>runJobMonitoringTutorial</id>
            <build>
                <defaultGoal>exec:java</defaultGoal>
                <plugins>
                    <plugin>
                        <groupId>org.codehaus.mojo</groupId>
                        <artifactId>exec-maven-plugin</artifactId>
                        <version>${exec-maven-plugin-version}</version>
                        <configuration>
                            <mainClass>org.easybatch.tutorials.advanced.jmx.JobMonitoringTutorial</mainClass>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <profile>
            <id>runJobProgressTutorial</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.codehaus.mojo</groupId>
                        <artifactId>exec-maven-plugin</artifactId>
                        <version>${exec-maven-plugin-version}</version>
                        <goals>
                            <goal>exec</goal>
                        </goals>
                        <configuration>
                            <executable>java</executable>
                            <arguments>
                                <argument>-Dcom.sun.management.jmxremote.port=9999</argument>
                                <argument>-Dcom.sun.management.jmxremote.local.only=false</argument>
                                <argument>-Dcom.sun.management.jmxremote.authenticate=false</argument>
                                <argument>-Dcom.sun.management.jmxremote.ssl=false</argument>
                                <argument>-classpath</argument>
                                <classpath/>
                                <argument>org.easybatch.tutorials.advanced.jmx.JobProgressTutorial</argument>
                            </arguments>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <profile>
            <id>runJmsTutorial</id>
            <build>
                <defaultGoal>exec:java</defaultGoal>
                <plugins>
                    <plugin>
                        <groupId>org.codehaus.mojo</groupId>
                        <artifactId>exec-maven-plugin</artifactId>
                        <version>${exec-maven-plugin-version}</version>
                        <configuration>
                            <mainClass>org.easybatch.tutorials.advanced.jms.Launcher</mainClass>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <profile>
            <id>runJmsSender</id>
            <build>
                <defaultGoal>exec:java</defaultGoal>
                <plugins>
                    <plugin>
                        <groupId>org.codehaus.mojo</groupId>
                        <artifactId>exec-maven-plugin</artifactId>
                        <version>${exec-maven-plugin-version}</version>
                        <configuration>
                            <mainClass>org.easybatch.tutorials.advanced.jms.JMSSenderLauncher</mainClass>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>

    </profiles>

</project>
`

**Comment by benas** [comment]
Ok now I see your problem.

you changed the wrong line (and not all easy batch artifacts btw, only `easybatch-core`), I should have precised which line exactly. It's line N7 that you should change: https://github.com/EasyBatch/easybatch-tutorials/blob/master/pom.xml#L7

like this:

```diff
<artifactId>easybatch-tutorials</artifactId>
-<version>5.0.0</version>
+<version>5.1.0-SNAPSHOT</version>
<packaging>jar</packaging>
```

The rest of the file should be the same. `${project.version}` will refer to this property to import the right dependencies.

Can you retry with this?

**Comment by gamebecks** [comment]
Hi Mahmoud,
                       Sry for the late reply. Actually ours team is using nexus as main repo and there is access issue with the same. Neither can i indirectly plug to  5.1.0-SNAPSHOT repo via proxy as it again requires access to pass. But soon we will upgrade to 5.1.0-SNAPSHOT and only then will I be able to verify it. Also, in addition, job/batch stop functionality is an imp requirement. I hope its been taken care of in 5.1.0-SNAPSHOT.

Regards,

**Comment by benas** [comment]
No problem. I'm planning to release v5.1 in the next few days anyway. keep tuned.

The job interruption feature is also included in v5.1.
